<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_61ec124fb4968',
        'title' => 'Menu Source - Menu',
        'fields' => array(
            array(
                'key' => 'field_61ec12592d3b2',
                'label' => 'Menu',
                'name' => 'menu_source_menu',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'main-menu' => 'Main Menu',
                    'main-right' => 'Main Right',
                    'none' => 'None',
                ),
                'default_value' => 'None',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_61f155969b9a5',
                'label' => 'Classes',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61f1559d9b9a6',
                'label' => 'Unordered List Classes',
                'name' => 'unordered_list_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'pl-4',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61f155b39b9a7',
                'label' => 'List Item Classes',
                'name' => 'list_item_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'border-l-2 border-zinc-700 pl-4 relative hover:border-amber-400',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61f155bc9b9a8',
                'label' => 'Link Classes',
                'name' => 'link_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'text-blue-400 hover:underline',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'sidebar_creator',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_61f158f8008dc',
        'title' => 'Menu Source - Rawcode',
        'fields' => array(
            array(
                'key' => 'field_61f158f80b3fe',
                'label' => 'Rawcode',
                'name' => 'rawcode',
                'type' => 'textarea',
                'instructions' => 'Add any HTML in here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'ue__codemirror',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'show_column' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'sidebar_creator',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_61ec0bcedd404',
        'title' => 'Menu Source - Taxonomy',
        'fields' => array(
            array(
                'key' => 'field_61ec0bef8d677',
                'label' => 'Taxonomy',
                'name' => 'menu_source_taxonomy',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'category' => 'category',
                    'post_tag' => 'post_tag',
                    'nav_menu' => 'nav_menu',
                    'link_category' => 'link_category',
                    'post_format' => 'post_format',
                    'wp_theme' => 'wp_theme',
                    'syllabus_category' => 'syllabus_category',
                    'syllabus_tags' => 'syllabus_tags',
                    'none' => 'None',
                ),
                'default_value' => 'None',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_61f154553ad6f',
                'label' => 'Posts',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61efbf216021a',
                'label' => 'List Posts',
                'name' => 'list_posts',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61efd1d67e0ae',
                'label' => 'List Parent Posts',
                'name' => 'list_parent_posts',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61fa7dc3b0bc1',
                'label' => 'Post Query',
                'name' => 'post_query',
                'type' => 'textarea',
                'instructions' => 'Additional get_posts() parameters as a URL string format. Uses parse_str().',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'ue__codemirror',
                    'id' => '',
                ),
                'default_value' => 'meta_key=award_level&meta_type=NUMERIC&orderby=meta_value_num&order=ASC',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_61f153758ade1',
                'label' => 'Classes',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61f153138addd',
                'label' => 'Unordered List Classes',
                'name' => 'unordered_list_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'pl-4 tab',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61f153368adde',
                'label' => 'List Item Classes',
                'name' => 'list_item_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'border-l-2 border-zinc-700 pl-4 relative hover:border-amber-400 tab-content',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61f153438addf',
                'label' => 'Link Classes',
                'name' => 'link_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'text-blue-400 hover:underline',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61fa62f65ce7d',
                'label' => 'Expand',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61fa63065ce7e',
                'label' => 'Auto Expand',
                'name' => 'auto_expand',
                'type' => 'true_false',
                'instructions' => 'Automatically open menu up to current page.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'syllabus_settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_61ec0680e7865',
        'title' => 'Sidebar instance',
        'fields' => array(
            array(
                'key' => 'field_61ec07760b5dc',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61ec0b3764af1',
                'label' => 'Enabled',
                'name' => 'enabled',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61ec068e039f7',
                'label' => 'Sidebar Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61ec17f1562fe',
                'label' => 'Shortcode Slug',
                'name' => 'slug',
                'type' => 'text',
                'instructions' => 'No spaces, only use underscores or hypens. Name of shortcode to be registered.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61ec07a20b5de',
                'label' => 'Structure',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61ec1c44e0542',
                'label' => 'Structure',
                'name' => 'structure',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_61ec0bae1bfd7',
                        'label' => 'Source',
                        'name' => 'structure_source',
                        'type' => 'flexible_content',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layouts' => array(
                            'layout_61ec0bbb95080' => array(
                                'key' => 'layout_61ec0bbb95080',
                                'name' => 'taxonomy',
                                'label' => 'Taxonomy',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61ec12771bfd8',
                                        'label' => 'Taxonomy',
                                        'name' => 'structure_taxonomy',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_61ec0bcedd404',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_61ec12921bfd9' => array(
                                'key' => 'layout_61ec12921bfd9',
                                'name' => 'menu',
                                'label' => 'Menu',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61ec129a1bfda',
                                        'label' => 'Menu',
                                        'name' => 'structure_menu',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_61ec124fb4968',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                            'layout_61f1594810ec7' => array(
                                'key' => 'layout_61f1594810ec7',
                                'name' => 'rawcode',
                                'label' => 'Rawcode',
                                'display' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_61f1594d10ec8',
                                        'label' => 'Rawcode',
                                        'name' => 'rawcode',
                                        'type' => 'clone',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'clone' => array(
                                            0 => 'group_61f158f8008dc',
                                        ),
                                        'display' => 'seamless',
                                        'layout' => 'block',
                                        'prefix_label' => 0,
                                        'prefix_name' => 0,
                                    ),
                                ),
                                'min' => '',
                                'max' => '',
                            ),
                        ),
                        'button_label' => 'Add Row',
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_61efd5a65839d',
                'label' => 'Wrapper',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61efff5af7cde',
                'label' => 'wrapper classes (div)',
                'name' => 'wrapper_classes',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'show_column' => 0,
                'show_column_sortable' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61efe62838a42',
                'label' => 'Code',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61eff244cecd8',
                'label' => 'Help',
                'name' => 'help',
                'type' => 'textarea',
                'instructions' => 'This is the structure of the code when rendered on the page.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'ue__codemirror',
                    'id' => '',
                ),
                'default_value' => '<ul>								// Top Level unordered list open
            <li><a></a></li>				// List item open & close + Link open & close.
            <li>							// List Item open & close.
                     <a></a>					// Link open & close.
                     <ul>						// Unordered list open
                                <li>					// List Item open
                    <a>					// Link open
                        Heading(count)	// Count
                    </a>				// Link Close
                    </li>					// List item close
                     </ul>						// Unordered list close
            </li>							// List item close
    </ul>								// Top Level - Unordered list close
    
    The boxes below allow you to inject code around any of the opening or closing tags within the structure. It also includes around the (20) count number too. 
    
    Usage of moustache {{name}}, {{tax_id}}, etc.. allowed in textbox to substitute for real value. This will be a WP_Term object.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 4,
                'new_lines' => '',
                'show_column' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
            array(
                'key' => 'field_61f0ff637d334',
                'label' => 'Prefix Suffix',
                'name' => 'prefix_suffix',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_61f101b8141fc',
                        'label' => 'Top Level &lt;ul&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61f101e4141fd',
                        'label' => 'Prefix Top Unordered List Open',
                        'name' => 'prefix_top_unordered_list_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before top-level unordered list open (ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f101e7141fe',
                        'label' => 'Suffix Top Unordered List Open',
                        'name' => 'suffix_top_unordered_list_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after top-level unordered list open (ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '<input type="checkbox" id="chck{{term_id}}">
    <label class="tab-label" for="chck{{term_id}}">OPEN</label>',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f10207141ff',
                        'label' => 'Top Level &lt;/ul&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61f1020e14200',
                        'label' => 'Prefix Top Unordered List Close',
                        'name' => 'prefix_top_unordered_list_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before top-level unordered list close (/ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1021314201',
                        'label' => 'Suffix Top Unordered List Close',
                        'name' => 'suffix_top_unordered_list_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after top-level unordered list close (/ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1009247cf0',
                        'label' => '&lt;ul&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61eff37c43120',
                        'label' => 'Prefix Unordered List Open',
                        'name' => 'prefix_unordered_list_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before unordered list open (ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61eff3b043121',
                        'label' => 'Suffix Unordered List Open',
                        'name' => 'suffix_unordered_list_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after unordered list open (ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '<input type="checkbox" id="chck{{term_id}}">
    <label class="tab-label" for="chck{{term_id}}">{{name}}</label>',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1009847cf1',
                        'label' => '&lt;/ul&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61eff3c643122',
                        'label' => 'Prefix Unordered List Close',
                        'name' => 'prefix_unordered_list_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before unordered list close (/ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61eff3f643123',
                        'label' => 'Suffix Unordered List Close',
                        'name' => 'suffix_unordered_list_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after unordered list close (/ul)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1007a47cee',
                        'label' => '&lt;li&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61efed5bdcc36',
                        'label' => 'Prefix List Item Open',
                        'name' => 'prefix_list_item_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before list item open (li)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61efed5fdcc37',
                        'label' => 'Suffix List Item Open',
                        'name' => 'suffix_list_item_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after list item open(LI)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1008947cef',
                        'label' => '&lt;/li&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61efef2084bbc',
                        'label' => 'Prefix List Item Close',
                        'name' => 'prefix_list_item_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before list item close (/li)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61efef2884bbd',
                        'label' => 'Suffix List Item Close',
                        'name' => 'suffix_list_item_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after list item close (/li)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f0ffb61fc66',
                        'label' => '&lt;a&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61efe67738a43',
                        'label' => 'Prefix Link Open',
                        'name' => 'prefix_link_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before opening A tag.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61efe68a38a44',
                        'label' => 'Suffix Link Open',
                        'name' => 'suffix_link_open',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after opening A tag.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f0ffd11fc67',
                        'label' => '&lt;/a&gt;',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61efeb12db750',
                        'label' => 'Prefix Link Close',
                        'name' => 'prefix_link_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before closing A tag.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61efeb1edb751',
                        'label' => 'Suffix Link Close',
                        'name' => 'suffix_link_close',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after closing A tag.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61f1005f47ced',
                        'label' => '(Count)',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_61efec5138eec',
                        'label' => 'Prefix Count',
                        'name' => 'prefix_count',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately before (20) number count.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                    array(
                        'key' => 'field_61efec5538eed',
                        'label' => 'Suffix Count',
                        'name' => 'suffix_count',
                        'type' => 'textarea',
                        'instructions' => 'Add code immediately after (20) number count.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => 'ue__codemirror',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => '',
                        'show_column' => 0,
                        'show_column_weight' => 1000,
                        'allow_quickedit' => 0,
                        'allow_bulkedit' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_61effe274c4bc',
                'label' => 'Style',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_61effe314c4bd',
                'label' => 'style',
                'name' => 'style',
                'type' => 'textarea',
                'instructions' => 'Add CSS styles. No need to wrap in style tags - automatically done.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'ue__codemirror',
                    'id' => '',
                ),
                'default_value' => '/* -------------------
    * 
    * IF :checked, then display all siblings by
    * changing the max-height to 100vh;
    * 
    */
    input:checked ~ .tab-content {
        max-height: 2000vh;
    }
    
    
    /*
    * Hide the checkbox 
    */
    input {
        position: absolute;
        opacity: 0;
        z-index: -1;
    }
    
    
    /*
    * Hide any overflow - which is the content
    */
    .tab {
        width: 100%;
        overflow: hidden;
    }
    
    
    /*
    * Make the label a block element
    */
    .tab-label {
        display: block;
        cursor: pointer;
    }
    
    
    /*
    * Hide the content by default with a max-height:0
    */
    .tab-content {
        max-height: 0;
        transition: all .35s;
    }',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'show_column' => 0,
                'show_column_weight' => 1000,
                'allow_quickedit' => 0,
                'allow_bulkedit' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'sidebar_creator',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_61ebff507b16b',
        'title' => 'Sidebar Menu Creator',
        'fields' => array(
            array(
                'key' => 'field_61ec0560be2ad',
                'label' => 'Sidebars',
                'name' => 'sidebars',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_61ec06f9ad64b' => array(
                        'key' => 'layout_61ec06f9ad64b',
                        'name' => 'sidebar_instance',
                        'label' => 'Sidebar Instance',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_61ec0712d395a',
                                'label' => '',
                                'name' => '',
                                'type' => 'clone',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'clone' => array(
                                    0 => 'group_61ec0680e7865',
                                ),
                                'display' => 'seamless',
                                'layout' => 'block',
                                'prefix_label' => 0,
                                'prefix_name' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add New Sidebar',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'sidebar_creator',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;